nelmio_cors:
    defaults:
        allow_origin: ['https://127.0.0.1:9550', 'https://localhost:9550']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        max_age: 3600
        expose_headers: ['Link']
    paths:
        '^/': ~